[package]
name = "passkeygenie"
version = "1.0.0"
edition = "2021"
authors = ["Your Name"]
description = "Password generator written in Rust"

[dependencies]
rand = "0.8.5"
clap = "3.2.16"

[features]
default = ["cli"]
cli = ["clap"]